version: "3.5"
services:
  mongo:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  
  trotter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trotter
    environment:
      - MONGODB_URL="mongodb://mongo/trotternfts?readPreference=primary&appname=MongoDB%20Compass&ssl=false"
      - MNEMONIC=input engage salon smooth choose buffalo priority february advice crop visit stand
      - TROTTER_NODE_ENV=develop
    # rate limiting / timeout
      - LIMIT=10
      - TTL=60
    #  - ADMIN_USERNAME=""
    #  - ADMIN_PASSWORD=""
      ## Supported networks
      - API_MATIC_TESTNET=https://rpc-mumbai.maticvigil.com/
      - API_MATIC_MAINNET=https://rpc-mainnet.maticvigil.com/
      - API_ETH_TESTNET=https://rinkeby.infura.io/v3/f3f30b367c6c45c093d0a7c7bd7709fa
      - API_ETH_MAINNET=https://mainnet.infura.io/v3/f3f30b367c6c45c093d0a7c7bd7709fa
      - API_BSC_TESTNET=https://data-seed-prebsc-1-s2.binance.org:8545
      - API_BSC_MAINNET=https://bsc-dataseed.binance.org
      - API_DEFAULT_NETWORK=API_MATIC_TESTNET
      ## Contract addresses
      - NFT_CONTRACT_MATIC_MAINNET=0xb8Ce1A790f250d8141cDc1DB212546E30186843E
      - NFT_CONTRACT_ETH_MAINNET=
      - NFT_CONTRACT_BSC_MAINNET=0x820308811825CdFd028E591A7C582d0Fc582395d
      - NFT_CONTRACT_MATIC_TESTNET=0xF17874BE1baBbE00fB31FcD05BF79bF3708acc3e
      - NFT_CONTRACT_ETH_TESTNET=0x3cBB1263bEBFbc056D76f5560393BBAe883f438d
      - NFT_CONTRACT_BSC_TESTNET=0x2a3dCe98fcE92F3c6F1a9f5BEffa9Bd2e4a5CD4c
      # - NFT_CONTRACT_BSC_TESTNET=0xFeCe4Fc6D3F64a8f14ad061D0d30BAD422fDD452
      ## Ipfs config
      - IPFS_PINN=false
      - IPFS_HOST=ipfs.infura.io
      - IPFS_PORT=5001

    ports:
      - 3000:3000
    depends_on:
      - mongo
    restart: unless-stopped
