version: "3.5"
services:
  mongo:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  
  trotter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trotter
    environment:
      - MONGODB_URL="mongodb://mongo/trotternfts?readPreference=primary&appname=MongoDB%20Compass&ssl=false"
    ports:
      - 3000:3000
    depends_on:
      - mongo
    restart: unless-stopped
