version: "3.5"
services:
  mongo:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped

  ipfs:
    image: ghcr.io/linuxserver/ipfs
    container_name: ipfs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./ipfs:/config
    ports:
    # - 80:80 # webui
      - 4001:4001 # p2p network port
      - 127.0.0.1:5001:5001 # api port
    #  - 8080:8080 # gateway port
    restart: unless-stopped
    depends_on:
      - trotter

  trotter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trotter
    environment:
      - MONGODB_URL="mongodb://mongo/trotternfts?readPreference=primary&appname=MongoDB%20Compass&ssl=false"
      - MNEMONIC=input engage salon smooth choose buffalo priority february advice crop visit stand
      - TROTTER_NODE_ENV=develop
      ## rate limiting / timeout
      - LIMIT=10
      - TTL=60
      ## Auth
      ### Trotter will not take auth into consideration unless TROTTER_MODE is set to "prod"
      - ADMIN_USERNAME="admin"
      - ADMIN_PASSWORD="PeHonWat="
      ## Supported networks
      - API_MATIC_TESTNET=https://rpc-mumbai.maticvigil.com/
      - API_MATIC_MAINNET=https://rpc-mainnet.maticvigil.com/
      - API_ETH_TESTNET=https://rinkeby.infura.io/v3/eb2a4aeb4d414af48b46709684b5d1dd
      - API_ETH_MAINNET=https://mainnet.infura.io/v3/eb2a4aeb4d414af48b46709684b5d1dd
      - API_BSC_TESTNET=https://data-seed-prebsc-1-s2.binance.org:8545
      - API_BSC_MAINNET=https://bsc-dataseed.binance.org
      - API_DEFAULT_NETWORK=API_ETH_TESTNET
      ## Contract addresses
      - NFT_CONTRACT_MATIC_MAINNET=0xF7cfB64B17e20Dc6a076BaC6DD2dD855a2C1950d
      - NFT_CONTRACT_ETH_MAINNET=
      - NFT_CONTRACT_BSC_MAINNET=0x099b22707fBFaa108058f542670c2501dcdc4e91
      - NFT_CONTRACT_MATIC_TESTNET=0xF17874BE1baBbE00fB31FcD05BF79bF3708acc3e
      - NFT_CONTRACT_ETH_TESTNET=0xEa8F04E5C25654eFc29d75eFF28828064a918509
      - NFT_CONTRACT_BSC_TESTNET=0x2a3dCe98fcE92F3c6F1a9f5BEffa9Bd2e4a5CD4c
      ## Ipfs config
      - IPFS_PINN=false
      - IPFS_HOST=ipfs.infura.io
      - IPFS_PORT=5001
      - IPFS_PROTOCOL=https

    ports:
      - 3000:3000
    depends_on:
      - mongo
    restart: unless-stopped
